### ISSUE TITLE
InSAR fails with `range position of phase reference point outside of image segment` during phase unwrapping

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-gamma#583]
Three jobs failed with this error on 2024-07-24

- https://hyp3-api.asf.alaska.edu/jobs/7fe2621a-9f87-4f6f-9f6c-b9fcd39d7641
- https://hyp3-api.asf.alaska.edu/jobs/72c5e504-81d9-4add-8249-43ddaf656607
- https://hyp3-api.asf.alaska.edu/jobs/f40e0181-bee0-44f1-ac83-70223b5d2a02

```
Traceback (most recent call last):
  File "/usr/local/bin/hyp3_gamma", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/hyp3_gamma/__main__.py", line 39, in main
    process_entry_point.load()()
  File "/usr/local/lib/python3.10/dist-packages/hyp3_gamma/__main__.py", line 186, in insar
    product_name = insar_sentinel_gamma(
  File "/usr/local/lib/python3.10/dist-packages/hyp3_gamma/insar/ifm_sentinel.py", line 427, in insar_sentinel_gamma
    coords, ref_point_info = unwrapping_geocoding(reference, secondary, step="man", rlooks=rlooks, alooks=alooks,
  File "/usr/local/lib/python3.10/dist-packages/hyp3_gamma/insar/unwrapping_geocoding.py", line 280, in unwrapping_geocoding
    mcf_log = execute(f"mcf {ifgf}.adf {ifgname}.adf.cc {out_file} {ifgname}.adf.unw {width} {trimode} 0 0"
  File "/usr/local/lib/python3.10/dist-packages/hyp3lib/execute.py", line 78, in execute
    raise ExecuteError(tool + ': ' + line)
hyp3lib.exceptions.ExecuteError: mcf: ERROR: range position of phase reference point outside of image segment: 3372  bounds: 0  3372
```

Complete log file: [7fe2621a-9f87-4f6f-9f6c-b9fcd39d7641.log](https://github.com/user-attachments/files/16364735/7fe2621a-9f87-4f6f-9f6c-b9fcd39d7641.log)

**Comment by asjohnston-asf** [comment]
Two more examples from 2024-08-12
- https://hyp3-api.asf.alaska.edu/jobs/27860ba9-f714-4acd-891d-883d0a0e3693
- https://hyp3-api.asf.alaska.edu/jobs/9de84d62-ecc6-4337-86a1-38cbf5211e71
